### ISSUE TITLE
FrontEndTest Crashes

### ISSUE THREAD

**Issue by ghost** [StartNine/start9-api#1]
![image](https://user-images.githubusercontent.com/37509156/39411647-c69e411e-4bd3-11e8-958b-3c22641dba82.png)

Help

**Comment by reflectronic** [comment]
do you have a specific error code you can show us

**Comment by ghost** [comment]
not really it doesn't say Details on the stopped working messege

**Comment by reflectronic** [comment]
oh I think I know why. you're on windows 7, and we're doing some unguarded live tile checks. you're not missing out on much though, the entire application is just testing live tiles

**Comment by ghost** [comment]
Im on windows 8.1

**Comment by reflectronic** [comment]
oh it's probably not finding the application then

**Comment by ghost** [comment]
How do I make it find the app then

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/37509156/39411704-0910d6dc-4bd5-11e8-8fd4-4e319649b9d6.png)

Um this MainWindow is awkward

**Comment by Splitwirez** [comment]
It's hardcoded to one specific version of the app. Literally the exact same issue as the Double-Decker-Bar ._.

**Comment by ghost** [comment]
Oh RIP

**Comment by Splitwirez** [comment]
...which, by the way, isn't actually an "issue" at all.

**Comment by reflectronic** [comment]
we'll fix it later

**Comment by ghost** [comment]
k then
